# Site settings
title: Urban Infrastructure Lab at the University of Washington
email: urbinfra@uw.edu
description: > # this means to ignore newlines until "baseurl:"
        Website of the Urban Infrastructure Lab at the University of Washington
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://urbaninfra.washington.edu" # the base hostname & protocol for your site

github_username: urbaninfra 

# Build settings
markdown: kramdown
